#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 27 20:04:51 2020

@author: joshuajacob
"""

import decimal

z = 0
dot100 = decimal.Context(prec=110)

for a in range(1,100):
    if len(str(a**0.5)) > 3:
        num = decimal.Decimal(a)
        print([int(x) for x in str(num.sqrt(dot100)) if x != '.'][:100])
        print(len([int(x) for x in str(num.sqrt(dot100)) if x != '.'][:100]))
        z += sum([int(x) for x in str(num.sqrt(dot100)) if x != '.'][:100])
        print(z,a)
        
